### ISSUE TITLE
Building REST APIs with Go and TDD

### ISSUE THREAD

**Issue by jasonmccallister** [norfolkgo/logistics#2]
Not sure if this is the correct format, but I'm up for giving a talk on building REST APIs with Go. 

High-level summary/agenda:

- Application Overview
- What is REST?
- Setup with Docker
- Writing Our First Test
- Making Our First Endpoint
- Considerations
- Additional Resources

**Comment by troy0820** [comment]
Just confirming with the venue and since you volunteered first, you got it @jasonmccallister.

**Comment by troy0820** [comment]
Closing issue to confirm that @jasonmccallister is speaking in October.  #3 explains agenda
